In [1]:
import numpy as np
from keras.models import Sequential
from keras.layers import Dense, Activation, Embedding,Flatten, Dropout
from keras.optimizers import RMSprop,SGD

Using TensorFlow backend.


Lecture des données
===================

In [2]:
raw_dataset = open("../data/multiclass2.dat")

In [3]:
dataset = list([ line.split() for line in raw_dataset])
print(dataset)

[['x', 'x', 'x', 'A'], ['x', 'x', 'y', 'A'], ['x', 'x', 'z', 'A'], ['x', 'y', 'x', 'D'], ['x', 'y', 'y', 'B'], ['x', 'y', 'z', 'D'], ['x', 'z', 'x', 'D'], ['x', 'z', 'y', 'D'], ['x', 'z', 'z', 'C'], ['y', 'x', 'x', 'A'], ['y', 'x', 'y', 'D'], ['y', 'x', 'z', 'D'], ['y', 'y', 'x', 'B'], ['y', 'y', 'y', 'B'], ['y', 'y', 'z', 'B'], ['y', 'z', 'x', 'D'], ['y', 'z', 'y', 'D'], ['y', 'z', 'z', 'C'], ['z', 'x', 'x', 'A'], ['z', 'x', 'y', 'D'], ['z', 'x', 'z', 'D'], ['z', 'y', 'x', 'D'], ['z', 'y', 'y', 'B'], ['z', 'y', 'z', 'D'], ['z', 'z', 'x', 'C'], ['z', 'z', 'y', 'C'], ['z', 'z', 'z', 'C']]


Codage des données
==================

In [4]:
x_set = set([])
for line in dataset:
    x_set.update(line[:-1])
x_codes =  dict([(x,idx) for idx,x in enumerate(x_set)])
print(x_codes)

{'x': 2, 'z': 1, 'y': 0}


In [5]:
y_set = set([])
for line in dataset:
    y_set.add(line[-1])
rev_y_codes = list(y_set)
y_codes = dict([(y,idx) for (idx,y) in enumerate(rev_y_codes)])
print(y_codes)

{'C': 0, 'D': 3, 'A': 2, 'B': 1}


In [6]:
X      = list([x_codes[elt] for elt in line[:-1]] for line in dataset)
ycodes = list([y_codes[line[-1]] for line in dataset])
print(X)
print(ycodes)

[[2, 2, 2], [2, 2, 0], [2, 2, 1], [2, 0, 2], [2, 0, 0], [2, 0, 1], [2, 1, 2], [2, 1, 0], [2, 1, 1], [0, 2, 2], [0, 2, 0], [0, 2, 1], [0, 0, 2], [0, 0, 0], [0, 0, 1], [0, 1, 2], [0, 1, 0], [0, 1, 1], [1, 2, 2], [1, 2, 0], [1, 2, 1], [1, 0, 2], [1, 0, 0], [1, 0, 1], [1, 1, 2], [1, 1, 0], [1, 1, 1]]
[2, 2, 2, 3, 1, 3, 3, 3, 0, 2, 3, 3, 1, 1, 1, 3, 3, 0, 2, 3, 3, 3, 1, 3, 0, 0, 0]


Keras attend une matrice de valeurs Y...

In [7]:
Y = np.zeros((len(dataset),len(y_codes)))
for (idx,elt) in enumerate(ycodes):
    Y[idx,elt] = 1.0
print(Y)

[[ 0.  0.  1.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  0.  1.]
 [ 0.  0.  0.  1.]
 [ 0.  0.  0.  1.]
 [ 1.  0.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]
 [ 0.  0.  0.  1.]
 [ 0.  1.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  0.  1.]
 [ 0.  0.  0.  1.]
 [ 1.  0.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]
 [ 0.  0.  0.  1.]
 [ 0.  0.  0.  1.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  0.  1.]
 [ 1.  0.  0.  0.]
 [ 1.  0.  0.  0.]
 [ 1.  0.  0.  0.]]


Structure du modèle
===================

In [8]:
x_size = len(x_codes)
y_size = len(y_codes)
embedding_size = 2
hidden_size    = 3
model = Sequential()
model.add(Embedding(x_size,embedding_size,input_length=3)) #3 x symbols predict an Y
model.add(Flatten()) 
model.add(Dense(hidden_size))
model.add(Activation('tanh'))
model.add(Dense(y_size))
model.add(Activation('softmax'))

Descente de gradient
====================

In [9]:
sgd = RMSprop(lr=0.1)
model.compile(optimizer=sgd,loss='categorical_crossentropy',metrics=['accuracy'])
model.fit(X,Y,epochs=50)

Epoch 1/50
27/27 [==============================] - 0s - loss: 1.3865 - acc: 0.1111
Epoch 2/50
27/27 [==============================] - 0s - loss: 1.3298 - acc: 0.4444
Epoch 3/50
27/27 [==============================] - 0s - loss: 1.1247 - acc: 0.5926
Epoch 4/50
27/27 [==============================] - 0s - loss: 0.9553 - acc: 0.6296
Epoch 5/50
27/27 [==============================] - 0s - loss: 0.8848 - acc: 0.6667
Epoch 6/50
27/27 [==============================] - 0s - loss: 0.7728 - acc: 0.6667
Epoch 7/50
27/27 [==============================] - 0s - loss: 0.6837 - acc: 0.7037
Epoch 8/50
27/27 [==============================] - 0s - loss: 0.6168 - acc: 0.8519
Epoch 9/50
27/27 [==============================] - 0s - loss: 0.5696 - acc: 0.8889
Epoch 10/50
27/27 [==============================] - 0s - loss: 0.5305 - acc: 0.8889
Epoch 11/50
27/27 [==============================] - 0s - loss: 0.5075 - acc: 0.9259
Epoch 12/50
27/27 [==============================] - 0s - loss: 0.4951 - a

Test 
====

On commence par coder numériquement les données...

In [10]:
test_set = [['x','x','y'],['z','y','y']]
testX = list([[x_codes[elt] for elt in line] for line in test_set])
print(testX)

[[2, 2, 0], [1, 0, 0]]


On réalise l'ensemble des prédictions en une fois...

In [11]:
model.predict(testX)

array([[  4.50881430e-07,   2.81450957e-06,   9.61334884e-01,
          3.86618860e-02],
       [  5.57058491e-04,   9.92498577e-01,   1.05758372e-04,
          6.83863275e-03]], dtype=float32)

On applique une règle de décision et on décode la représentation numérique (le plus haut score l'emporte)...

In [12]:
probs = model.predict(testX)
Yvals = [rev_y_codes[np.argmax(line)] for line in probs]
print(Yvals)

['A', 'B']
