In [1]:
import numpy as np
from keras.models import Sequential
from keras.layers import Dense, Activation, Embedding,Flatten, Dropout
from keras.optimizers import RMSprop,SGD

Using TensorFlow backend.


Lecture des données
===================

In [2]:
raw_dataset = open("../data/multiclass2.dat")

In [3]:
dataset = list([ line.split() for line in raw_dataset])
print(dataset)

[['x', 'x', 'x', 'A'], ['x', 'x', 'y', 'A'], ['x', 'x', 'z', 'A'], ['x', 'y', 'x', 'D'], ['x', 'y', 'y', 'B'], ['x', 'y', 'z', 'D'], ['x', 'z', 'x', 'D'], ['x', 'z', 'y', 'D'], ['x', 'z', 'z', 'C'], ['y', 'x', 'x', 'A'], ['y', 'x', 'y', 'D'], ['y', 'x', 'z', 'D'], ['y', 'y', 'x', 'B'], ['y', 'y', 'y', 'B'], ['y', 'y', 'z', 'B'], ['y', 'z', 'x', 'D'], ['y', 'z', 'y', 'D'], ['y', 'z', 'z', 'C'], ['z', 'x', 'x', 'A'], ['z', 'x', 'y', 'D'], ['z', 'x', 'z', 'D'], ['z', 'y', 'x', 'D'], ['z', 'y', 'y', 'B'], ['z', 'y', 'z', 'D'], ['z', 'z', 'x', 'C'], ['z', 'z', 'y', 'C'], ['z', 'z', 'z', 'C']]


Codage des données
==================

In [4]:
x_set = set([])
for line in dataset:
    x_set.update(line[:-1])
x_codes =  dict([(x,idx) for idx,x in enumerate(x_set)])
print(x_codes)

{'z': 0, 'y': 1, 'x': 2}


In [5]:
y_set = set([])
for line in dataset:
    y_set.add(line[-1])
rev_y_codes = list(y_set)
y_codes = dict([(y,idx) for (idx,y) in enumerate(rev_y_codes)])
print(y_codes)

{'D': 0, 'A': 1, 'C': 3, 'B': 2}


In [6]:
X      = list([x_codes[elt] for elt in line[:-1]] for line in dataset)
ycodes = list([y_codes[line[-1]] for line in dataset])
print(X)
print(ycodes)

[[2, 2, 2], [2, 2, 1], [2, 2, 0], [2, 1, 2], [2, 1, 1], [2, 1, 0], [2, 0, 2], [2, 0, 1], [2, 0, 0], [1, 2, 2], [1, 2, 1], [1, 2, 0], [1, 1, 2], [1, 1, 1], [1, 1, 0], [1, 0, 2], [1, 0, 1], [1, 0, 0], [0, 2, 2], [0, 2, 1], [0, 2, 0], [0, 1, 2], [0, 1, 1], [0, 1, 0], [0, 0, 2], [0, 0, 1], [0, 0, 0]]
[1, 1, 1, 0, 2, 0, 0, 0, 3, 1, 0, 0, 2, 2, 2, 0, 0, 3, 1, 0, 0, 0, 2, 0, 3, 3, 3]


Keras attend une matrice de valeurs Y...

In [7]:
Y = np.zeros((len(dataset),len(y_codes)))
for (idx,elt) in enumerate(ycodes):
    Y[idx,elt] = 1.0
print(Y)

[[ 0.  1.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 1.  0.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 1.  0.  0.  0.]
 [ 1.  0.  0.  0.]
 [ 1.  0.  0.  0.]
 [ 0.  0.  0.  1.]
 [ 0.  1.  0.  0.]
 [ 1.  0.  0.  0.]
 [ 1.  0.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  1.  0.]
 [ 1.  0.  0.  0.]
 [ 1.  0.  0.  0.]
 [ 0.  0.  0.  1.]
 [ 0.  1.  0.  0.]
 [ 1.  0.  0.  0.]
 [ 1.  0.  0.  0.]
 [ 1.  0.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 1.  0.  0.  0.]
 [ 0.  0.  0.  1.]
 [ 0.  0.  0.  1.]
 [ 0.  0.  0.  1.]]


Structure du modèle
===================

In [8]:
x_size = len(x_codes)
y_size = len(y_codes)
embedding_size = 2
hidden_size    = 3
model = Sequential()
model.add(Embedding(x_size,embedding_size,input_length=3)) #3 x symbols predict an Y
model.add(Flatten()) 
model.add(Dense(hidden_size))
model.add(Activation('tanh'))
model.add(Dense(y_size))
model.add(Activation('softmax'))

Descente de gradient
====================

In [9]:
sgd = SGD(lr=0.0001)
model.compile(optimizer=sgd,loss='categorical_crossentropy',metrics=['accuracy'])
model.fit(X,Y,epochs=5)

Epoch 1/5
27/27 [==============================] - 0s - loss: 1.3932 - acc: 0.1852
Epoch 2/5
27/27 [==============================] - 0s - loss: 1.3932 - acc: 0.1852
Epoch 3/5
27/27 [==============================] - 0s - loss: 1.3931 - acc: 0.1852
Epoch 4/5
27/27 [==============================] - 0s - loss: 1.3931 - acc: 0.1852
Epoch 5/5
27/27 [==============================] - 0s - loss: 1.3931 - acc: 0.1852


Test 
====

On commence par coder numériquement les données...

In [10]:
test_set = [['x','x','y'],['z','y','y']]
testX = list([[x_codes[elt] for elt in line] for line in test_set])
print(testX)

[[2, 2, 1], [0, 1, 1]]


On réalise l'ensemble des prédictions en une fois...

In [11]:
model.predict(testX)

array([[ 0.25188926,  0.24439578,  0.25007284,  0.25364208],
       [ 0.24828842,  0.25700322,  0.25226   ,  0.24244834]], dtype=float32)

On applique une règle de décision et on décode la représentation numérique (le plus haut score l'emporte)...

In [12]:
probs = model.predict(testX)
Yvals = [rev_y_codes[np.argmax(line)] for line in probs]
print(Yvals)

['C', 'A']
